import './globals.css';
import { Signika } from 'next/font/google';

const signika = Signika({ subsets: ['latin'] });

export const metadata = {
  title: 'Digital Universe - Agencia de Marketing Digital',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='es'>
      <body className={signika.className}>{children}</body>
    </html>
  );
}
